name: Build and Push Tutor Open edX Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: 📥 Клонируем репозиторий
        uses: actions/checkout@v3

      # 2. Запускаем Docker-in-Docker
      - name: 🛠️ Настройка Docker-in-Docker
        run: |
          docker run --privileged \
            --name dind-container \
            -v "$(pwd):/workspace" \
            -w /workspace \
            -d docker:24-dind
          sleep 10

      # 3. Сборка Docker-образа
      - name: 🛠️ Сборка Docker-образа
        run: |
          docker exec dind-container docker build -t mistervkln/tutor-openedx -f /workspace/Dockerfile /workspace

      # 4. Логин в Docker Hub
      - name: 🔑 Логин в Docker Hub
        run: |
          docker exec dind-container sh -c "echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin"

      # 5. Публикация образа в Docker Hub
      - name: 🚢 Публикация образа в Docker Hub
        run: |
          docker exec dind-container docker push mistervkln/tutor-openedx
